server:
  port: 8082
spring:
  application:
    name: netdisk-common
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/      #服务注册中信地址，含有BASIC认证的用户名和密码
  instance:
    prefer-ip-address: true
