server:
  port: 8082
spring:
  application:
    name: netdisk-common
  datasource: # Oracle config only 4 lines 0.0
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
    username: netdisk
    password: netdisk123
    # here is druid configuration
    initialSize: 1
    minIdle: 3
    maxActive: 216
    maxWait: 30000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    #useGlobalDataSourceStat: true
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-wait: 100000
          max-idle: 10
          max-active: 100
      timeout: 5000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  instance:
    prefer-ip-address: true