server:
  port: 8080
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  server:
    renewalPercentThreshold: 0.49